### ISSUE TITLE
Unable to compile to device -- can you replicate?

### ISSUE THREAD

**Issue by CarlosMendonca** [Niashi24/bitset-simd-min#1]
Hey, thanks for putting the repo together. Las time I played with rust and Playdate was using https://github.com/pd-rs/crankstart, so this was a helpful to get back up to speed. Pinging here to avoid spamming https://github.com/bevyengine/bevy/issues/15460.

I've spent some time setting up my environment (WSL, Ubuntu 22.04) and I can compile and test on simulator, but not on device. Can you check on your side if `cargo playdate build --device` works?

I'm getting this error: https://github.com/boozook/playdate/discussions/423

**Comment by Niashi24** [comment]
Not getting any errors on my end building it for device, but I left some notes on your other issue.
